---
- name: Ansible Playbook -> Show Version Dell OS10 PLAY
  hosts: switches
  connection: network_cli
  gather_facts: false

#task number-1
  tasks:
    - name: get show version
      dellos10_command: 
        commands: 
#        -  show system version
#        -  show ip interface brief
        -  show interface vlan | grep up
      register: show_ver
    
    - debug: var=show_ver
...
